#!/bin/bash
set -ex

REPO=dist/repo
DIR=$(pwd)
echo $DIR

mkdir -p $(dirname "$REPO")

git clone git@github.com:hockeyhub/hockeyhub.github.io.git "$REPO"

if ./build "$REPO" ; then
    cd "$REPO"
    git add . && git commit -m 'update' && git push origin master
fi

cd "$DIR"
rm -rf "$REPO"
